// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#ifndef UI_SPLASH_H
#define UI_SPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Splash
extern void ui_Splash_screen_init(void);
extern void ui_Splash_screen_destroy(void);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_LabelTime;
extern void ui_event_ButtonClear(lv_event_t * e);
extern lv_obj_t * ui_ButtonClear;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_LabelContent;
// CUSTOM VARIABLES
extern lv_obj_t * uic_LabelContent;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

