// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * uic_LabelContent;
lv_obj_t * ui_Splash = NULL;
lv_obj_t * ui_LabelContent = NULL;
lv_obj_t * ui_LabelTime = NULL;
lv_obj_t * ui_ButtonClear = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_ButtonClear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Clear(e);
    }
}

// build funtions

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelContent = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_LabelContent, lv_pct(100));
    lv_obj_set_height(ui_LabelContent, lv_pct(80));
    lv_obj_set_align(ui_LabelContent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelContent, "hello");
    lv_obj_remove_flag(ui_LabelContent, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_text_font(ui_LabelContent, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_LabelTime, lv_pct(100));
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTime, "00:00");

    ui_ButtonClear = lv_button_create(ui_Splash);
    lv_obj_set_width(ui_ButtonClear, lv_pct(80));
    lv_obj_set_height(ui_ButtonClear, lv_pct(10));
    lv_obj_set_align(ui_ButtonClear, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ButtonClear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonClear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonClear, lv_color_hex(0x0A0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonClear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_ButtonClear);
    lv_obj_set_width(ui_Label4, lv_pct(100));
    lv_obj_set_height(ui_Label4, lv_pct(100));
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "清空");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xF6EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonClear, ui_event_ButtonClear, LV_EVENT_ALL, NULL);
    uic_LabelContent = ui_LabelContent;

}

void ui_Splash_screen_destroy(void)
{
    if(ui_Splash) lv_obj_del(ui_Splash);

    // NULL screen variables
    ui_Splash = NULL;
    uic_LabelContent = NULL;
    ui_LabelContent = NULL;
    ui_LabelTime = NULL;
    ui_ButtonClear = NULL;
    ui_Label4 = NULL;

}
