// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Splash.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * upanim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * min_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * sec_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * scrolldot_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_font3Alibaba);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
