// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#include "ui.h"

// Button_Clear moved to main.c to survive SquareLine re-export